/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_window1 (void)
{
  GtkWidget *window1;
  GtkWidget *fixed1;
  GtkWidget *entry1;
  GtkWidget *backspace;
  GtkWidget *CE;
  GtkWidget *zero;
  GtkWidget *seven;
  GtkWidget *eight;
  GtkWidget *nine;
  GtkWidget *four;
  GtkWidget *five;
  GtkWidget *six;
  GtkWidget *multiplication;
  GtkWidget *one;
  GtkWidget *two;
  GtkWidget *three;
  GtkWidget *substaction;
  GtkWidget *dot;
  GtkWidget *equal;
  GtkWidget *addition;
  GtkWidget *division;
  GtkWidget *PLUSMINUS;
  GtkWidget *CLEAR;

  window1 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window1), _("window1"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (window1), fixed1);

  entry1 = gtk_entry_new ();
  gtk_widget_show (entry1);
  gtk_fixed_put (GTK_FIXED (fixed1), entry1, 104, 16);
  gtk_widget_set_size_request (entry1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry1), 8226);

  backspace = gtk_button_new_with_mnemonic (_("bksp"));
  gtk_widget_show (backspace);
  gtk_fixed_put (GTK_FIXED (fixed1), backspace, 16, 64);
  gtk_widget_set_size_request (backspace, 70, 29);

  CE = gtk_button_new_with_mnemonic (_("CE"));
  gtk_widget_show (CE);
  gtk_fixed_put (GTK_FIXED (fixed1), CE, 96, 64);
  gtk_widget_set_size_request (CE, 67, 29);

  zero = gtk_button_new_with_mnemonic (_("0"));
  gtk_widget_show (zero);
  gtk_fixed_put (GTK_FIXED (fixed1), zero, 16, 256);
  gtk_widget_set_size_request (zero, 75, 29);

  seven = gtk_button_new_with_mnemonic (_("7"));
  gtk_widget_show (seven);
  gtk_fixed_put (GTK_FIXED (fixed1), seven, 16, 112);
  gtk_widget_set_size_request (seven, 68, 29);

  eight = gtk_button_new_with_mnemonic (_("8"));
  gtk_widget_show (eight);
  gtk_fixed_put (GTK_FIXED (fixed1), eight, 96, 112);
  gtk_widget_set_size_request (eight, 68, 29);

  nine = gtk_button_new_with_mnemonic (_("9"));
  gtk_widget_show (nine);
  gtk_fixed_put (GTK_FIXED (fixed1), nine, 192, 112);
  gtk_widget_set_size_request (nine, 67, 29);

  four = gtk_button_new_with_mnemonic (_("4"));
  gtk_widget_show (four);
  gtk_fixed_put (GTK_FIXED (fixed1), four, 16, 160);
  gtk_widget_set_size_request (four, 68, 29);

  five = gtk_button_new_with_mnemonic (_("5"));
  gtk_widget_show (five);
  gtk_fixed_put (GTK_FIXED (fixed1), five, 104, 160);
  gtk_widget_set_size_request (five, 76, 29);

  six = gtk_button_new_with_mnemonic (_("6"));
  gtk_widget_show (six);
  gtk_fixed_put (GTK_FIXED (fixed1), six, 192, 160);
  gtk_widget_set_size_request (six, 75, 29);

  multiplication = gtk_button_new_with_mnemonic (_("\303\227"));
  gtk_widget_show (multiplication);
  gtk_fixed_put (GTK_FIXED (fixed1), multiplication, 280, 160);
  gtk_widget_set_size_request (multiplication, 75, 29);

  one = gtk_button_new_with_mnemonic (_("1"));
  gtk_widget_show (one);
  gtk_fixed_put (GTK_FIXED (fixed1), one, 16, 208);
  gtk_widget_set_size_request (one, 75, 29);

  two = gtk_button_new_with_mnemonic (_("2"));
  gtk_widget_show (two);
  gtk_fixed_put (GTK_FIXED (fixed1), two, 104, 208);
  gtk_widget_set_size_request (two, 75, 29);

  three = gtk_button_new_with_mnemonic (_("3"));
  gtk_widget_show (three);
  gtk_fixed_put (GTK_FIXED (fixed1), three, 200, 208);
  gtk_widget_set_size_request (three, 76, 29);

  substaction = gtk_button_new_with_mnemonic (_("-"));
  gtk_widget_show (substaction);
  gtk_fixed_put (GTK_FIXED (fixed1), substaction, 288, 208);
  gtk_widget_set_size_request (substaction, 76, 29);

  dot = gtk_button_new_with_mnemonic (_("."));
  gtk_widget_show (dot);
  gtk_fixed_put (GTK_FIXED (fixed1), dot, 104, 256);
  gtk_widget_set_size_request (dot, 75, 29);

  equal = gtk_button_new_with_mnemonic (_("="));
  gtk_widget_show (equal);
  gtk_fixed_put (GTK_FIXED (fixed1), equal, 208, 256);
  gtk_widget_set_size_request (equal, 76, 29);

  addition = gtk_button_new_with_mnemonic (_("+"));
  gtk_widget_show (addition);
  gtk_fixed_put (GTK_FIXED (fixed1), addition, 296, 256);
  gtk_widget_set_size_request (addition, 76, 29);

  division = gtk_button_new_with_mnemonic (_("\303\267"));
  gtk_widget_show (division);
  gtk_fixed_put (GTK_FIXED (fixed1), division, 280, 112);
  gtk_widget_set_size_request (division, 67, 29);

  PLUSMINUS = gtk_button_new_with_mnemonic (_("\302\261"));
  gtk_widget_show (PLUSMINUS);
  gtk_fixed_put (GTK_FIXED (fixed1), PLUSMINUS, 280, 64);
  gtk_widget_set_size_request (PLUSMINUS, 67, 29);

  CLEAR = gtk_button_new_with_mnemonic (_("Clr"));
  gtk_widget_show (CLEAR);
  gtk_fixed_put (GTK_FIXED (fixed1), CLEAR, 192, 64);
  gtk_widget_set_size_request (CLEAR, 67, 29);

  g_signal_connect ((gpointer) backspace, "clicked",
                    G_CALLBACK (on_backspace_clicked),
                    NULL);
  g_signal_connect ((gpointer) CE, "clicked",
                    G_CALLBACK (on_CE_clicked),
                    NULL);
  g_signal_connect ((gpointer) zero, "clicked",
                    G_CALLBACK (on_zero_clicked),
                    NULL);
  g_signal_connect ((gpointer) seven, "clicked",
                    G_CALLBACK (on_seven_clicked),
                    NULL);
  g_signal_connect ((gpointer) eight, "clicked",
                    G_CALLBACK (on_eight_clicked),
                    NULL);
  g_signal_connect ((gpointer) nine, "clicked",
                    G_CALLBACK (on_nine_clicked),
                    NULL);
  g_signal_connect ((gpointer) four, "clicked",
                    G_CALLBACK (on_four_clicked),
                    NULL);
  g_signal_connect ((gpointer) five, "clicked",
                    G_CALLBACK (on_five_clicked),
                    NULL);
  g_signal_connect ((gpointer) six, "clicked",
                    G_CALLBACK (on_six_clicked),
                    NULL);
  g_signal_connect ((gpointer) multiplication, "clicked",
                    G_CALLBACK (on_multiplication_clicked),
                    NULL);
  g_signal_connect ((gpointer) one, "clicked",
                    G_CALLBACK (on_one_clicked),
                    NULL);
  g_signal_connect ((gpointer) two, "clicked",
                    G_CALLBACK (on_two_clicked),
                    NULL);
  g_signal_connect ((gpointer) three, "clicked",
                    G_CALLBACK (on_three_clicked),
                    NULL);
  g_signal_connect ((gpointer) substaction, "clicked",
                    G_CALLBACK (on_substaction_clicked),
                    NULL);
  g_signal_connect ((gpointer) dot, "clicked",
                    G_CALLBACK (on_dot_clicked),
                    NULL);
  g_signal_connect ((gpointer) equal, "clicked",
                    G_CALLBACK (on_equal_clicked),
                    NULL);
  g_signal_connect ((gpointer) addition, "clicked",
                    G_CALLBACK (on_addition_clicked),
                    NULL);
  g_signal_connect ((gpointer) division, "clicked",
                    G_CALLBACK (on_division_clicked),
                    NULL);
  g_signal_connect ((gpointer) PLUSMINUS, "clicked",
                    G_CALLBACK (on_PLUSMINUS_clicked),
                    NULL);
  g_signal_connect ((gpointer) CLEAR, "clicked",
                    G_CALLBACK (on_CLEAR_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window1, window1, "window1");
  GLADE_HOOKUP_OBJECT (window1, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (window1, entry1, "entry1");
  GLADE_HOOKUP_OBJECT (window1, backspace, "backspace");
  GLADE_HOOKUP_OBJECT (window1, CE, "CE");
  GLADE_HOOKUP_OBJECT (window1, zero, "zero");
  GLADE_HOOKUP_OBJECT (window1, seven, "seven");
  GLADE_HOOKUP_OBJECT (window1, eight, "eight");
  GLADE_HOOKUP_OBJECT (window1, nine, "nine");
  GLADE_HOOKUP_OBJECT (window1, four, "four");
  GLADE_HOOKUP_OBJECT (window1, five, "five");
  GLADE_HOOKUP_OBJECT (window1, six, "six");
  GLADE_HOOKUP_OBJECT (window1, multiplication, "multiplication");
  GLADE_HOOKUP_OBJECT (window1, one, "one");
  GLADE_HOOKUP_OBJECT (window1, two, "two");
  GLADE_HOOKUP_OBJECT (window1, three, "three");
  GLADE_HOOKUP_OBJECT (window1, substaction, "substaction");
  GLADE_HOOKUP_OBJECT (window1, dot, "dot");
  GLADE_HOOKUP_OBJECT (window1, equal, "equal");
  GLADE_HOOKUP_OBJECT (window1, addition, "addition");
  GLADE_HOOKUP_OBJECT (window1, division, "division");
  GLADE_HOOKUP_OBJECT (window1, PLUSMINUS, "PLUSMINUS");
  GLADE_HOOKUP_OBJECT (window1, CLEAR, "CLEAR");

  return window1;
}

